name: Node.js CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: cd into dir
      run: cd backendapp
    - name: Install dependencies
      run: npm install
    - name: Run start
      run: npm start

