on:
 push:
  branches:
   - master
   
jobs:
 updateAuthor:
  runs-on: ubuntu-latest
  steps:
   - name: checking out code
     uses: actions/checkout@v2
     
   - name: update author information
     run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > kamrankamrankhan
     
   - name: Raise PR
     uses: peter-evans/create-pull-request@v3
     with:
      branch: "auto-pr-branch"
      base: master
      title: "demo for auto pr"
      committer_name: kamrankamrankhan
      committer_email: kamrankamrankhan825@gmail.com
      author_name: kamrankamrankhan
      author-email: kamrankamrankhan825@gmail.com
      body:
       This is to show automatic pr creation
      token: ${{ secrets.GITHUB_TOKEN }}
      delete-branch: true 
